name: Validate Manifests
on: [pull_request]

jobs:
  validate-github-actions-workflows:
    name: Validate JSON Schemas
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate scehmas
      uses: dsanders11/json-schema-validate-action@v1.1.2
      with:
        schema: ./snippets/manifest-schema.json
        files: ./snippets/functions/**/**.json 
    - name: Test
      run: |
        content=`cat ./manifest.json`
        echo $content
        barf=${{fromJson($content)}}
        echo ${{ barf }}