name: Zip and Upload to S3 for Production

on:
  push:
    branches:
      - main

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir zip
      - run: zip -r zip/triggers-functions-examples.zip . -x ".DS_Store" ".git/*" ".github/*" ".gitignore" "./zip/" "README.md" "backend/*" "test/*" "tools/*"
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ./zip
          destination_dir: "v1/production"